/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qltv;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pham Ngoc Minh
 */
public class statisticalDetailTable extends javax.swing.JPanel {

    /**
     * Creates new form statisticalDetailTable
     */
    public statisticalDetailTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        date = new javax.swing.JRadioButton();
        month = new javax.swing.JRadioButton();
        year = new javax.swing.JRadioButton();
        detailCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        date.setText("Ngày");
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        month.setText("Tháng");
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        year.setText("Năm");

        detailCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn", "Toàn bộ", "Nhân viên", "Người mượn" }));
        detailCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailComboActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(date)
                        .addGap(169, 169, 169)
                        .addComponent(month)
                        .addGap(157, 157, 157)
                        .addComponent(year)
                        .addGap(0, 230, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(detailCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(month)
                    .addComponent(year)
                    .addComponent(date))
                .addGap(18, 18, 18)
                .addComponent(detailCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
        getTime();
    }//GEN-LAST:event_monthActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
        getTime();

    }//GEN-LAST:event_dateActionPerformed

    private void detailComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailComboActionPerformed
        // TODO add your handling code here:
        ConnectDB con = new ConnectDB();
        Connection c = con.getConnect();
        JComboBox<String> combo = (JComboBox<String>) evt.getSource();
        String selected = (String) combo.getSelectedItem();
        if (selected != null) {
            switch (selected) {
                case "Toàn bộ":
                    Table.setModel(new DefaultTableModel(new Object[] {"Số phiếu","Số tiền cọc", "Số tiền phạt"},0));
                    for(String s : getTime()) {
                        
                        
                        String sql = "select count() from qltv.loan_payment where Borrow_day like '" + s + "%'";
                        String sql2 = "select count(Pay_day) from qltv.loan_payment_de where Borrow_day like '" + s + "%'";
                        try {
                            PreparedStatement pst = c.prepareStatement(sql);
                            ResultSet rs = pst.executeQuery();
                            
                            
                        } catch (Exception e) {
                        }
                    }
                    
            }
        }

    }//GEN-LAST:event_detailComboActionPerformed

    

    private Set<String> getTime() {
        ConnectDB con = new ConnectDB();
        Connection c = con.getConnect();
        Set<String> list = new HashSet<>();
        String sql = "Select distinct Borrow_day from qltv.loan_payment";
        String sql2 = "Select distinct Pay_day from qltv.loan_payment_detail";
        try {
            PreparedStatement pst = c.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String s = rs.getString(1);
                if (month.isSelected()) {

                    s = s.substring(0, 7);
                } else if (year.isSelected()) {
                    s = s.substring(0, 4);
                }
                list.add(s);

            }

            PreparedStatement pst2 = c.prepareStatement(sql2);
            ResultSet rs2 = pst2.executeQuery();
            while (rs2.next()) {

                String s = rs2.getString(1);
                if (month.isSelected()) {

                    s = s.substring(0, 7);
                } else if (year.isSelected()) {
                    s = s.substring(0, 4);
                }
                list.add(s);
            }
        } catch (SQLException ex) {
            Logger.getLogger(statisticalDetailTable.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String str : list) {
            System.out.println(str);
        }
        return list;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JRadioButton date;
    private javax.swing.JComboBox<String> detailCombo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton month;
    private javax.swing.JRadioButton year;
    // End of variables declaration//GEN-END:variables
}
